server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.196.1:1111
management:
  endpoints:
    web:
      exposure:
        include: "*"