server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.196.1:1111
    sentinel:
      transport:
        dashboard: localhost:8081
        port: 8719   #默认8719端口，假如被占用会自动从8719开始一次扫面，直至找到未被占用的端口

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider
#激活sentinel对openFeign的支持
feign:
  sentinel:
    enabled: true