server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.196.1:1111
    sentinel:
      transport:
<<<<<<< HEAD
        dashboard: localhost:8081
        port: 8719   #默认8719端口，假如被占用会自动从8719开始一次扫面，直至找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: 139.196.196.1:1111
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
=======
        dashboard: localhost:8080
        port: 8719   #默认8719端口，假如被占用会自动从8719开始一次扫面，直至找到未被占用的端口
>>>>>>> origin/master
management:
  endpoints:
    web:
      exposure:
        include: "*"